<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>WpeBaker</AssemblyName>
    <Version>1.1.0-preview.1</Version>
    <RootNamespace>Baker.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Baker.Core/Baker.Core.csproj" /></ItemGroup>
</Project>
